// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZgjB8nBWXllHjDGni1X5GkRkMlDuScR8',
    appId: '1:642002750828:web:bc264a719c4e1fc10bb749',
    messagingSenderId: '642002750828',
    projectId: 'attandancesystem-b7467',
    authDomain: 'attandancesystem-b7467.firebaseapp.com',
    storageBucket: 'attandancesystem-b7467.appspot.com',
    measurementId: 'G-6Z6VGJCNPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8v8peh23_eSctMbtVGJM2FayEGNhVrYk',
    appId: '1:642002750828:android:da81644691cfd3090bb749',
    messagingSenderId: '642002750828',
    projectId: 'attandancesystem-b7467',
    storageBucket: 'attandancesystem-b7467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8uUYZ3ztUwI1XIggVi6odwhS1IJnwOc',
    appId: '1:642002750828:ios:ca80bf9d673c85a10bb749',
    messagingSenderId: '642002750828',
    projectId: 'attandancesystem-b7467',
    storageBucket: 'attandancesystem-b7467.appspot.com',
    iosClientId: '642002750828-q1nka4gbtb08os6pjhsdamtqljulbknr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attandanceApp',
  );
}
